Coloring and optimization
Bulbang/2048 pull request #4
Opened 2021-04-12 16:38 UTC by Bulbang

Added coloring and removed useless code

2021-04-13 06:30 UTC, bogdanbryzh-official requested changes

2021-04-13 06:30 UTC, bogdanbryzh-official commented on modules/front/classGameCell.js
> +    this.color = [
Why not hex?

2021-04-13 06:30 UTC, bogdanbryzh-official commented on yarn-error.log
> +Arguments:
Delete this file 'git rm yarn-error.log' and add to .gitignore

2021-04-13 06:30 UTC, bogdanbryzh-official commented on modules/back/classGameMatrix.js
> +import { getMaxRandom, getNewBase, isCellFree } from "./base.js";
Why " instead of '?

2021-04-14 19:07 UTC, Bulbang commented on modules/front/classGameCell.js
> +    this.color = [
Cuz I was manually iterating this colors in vs code)

2021-04-14 19:09 UTC, Bulbang commented on modules/back/classGameMatrix.js
> +import { getMaxRandom, getNewBase, isCellFree } from "./base.js";
Don`t understand essence of the question

2021-04-15 12:23 UTC, bogdanbryzh-official requested changes

2021-04-15 12:23 UTC, bogdanbryzh-official commented on modules/back/classGameMatrix.js
> +import { getMaxRandom, getNewBase, isCellFree } from "./base.js";
Single quotes are preferred for JS

2021-04-15 12:23 UTC, bogdanbryzh-official commented on .gitignore
> +yarn-error.log
https://github.com/github/gitignore/blob/master/Node.gitignore

2021-04-23 10:30 UTC, bogdanbryzh-official approved these changes

2021-04-27 16:03 UTC, closed without merging